# Generated by Django 4.2.4 on 2024-08-25 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام')),
                ('status', models.CharField(choices=[('CREATED', 'ایجاد شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تمام شده'), ('CANCELED', 'کنسل شده')], default='CREATED', max_length=50, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ماموریت',
                'verbose_name_plural': 'ماموریت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام')),
                ('status', models.CharField(choices=[('CREATED', 'ایجاد شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تمام شده'), ('CANCELED', 'کنسل شده'), ('COMPLETED_WITHOUT_RESULT', 'تمام شده بدون نتیجه')], max_length=50, verbose_name='وضعیت')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.mission', verbose_name='ماموریت')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', django_jalali.db.models.jDateTimeField(verbose_name='زمان ثبت')),
                ('deadline', django_jalali.db.models.jDateTimeField(verbose_name='ددلاین')),
                ('task_title', models.CharField(max_length=500, verbose_name='عنوان وظیفه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('CREATED', 'ایجاد شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تمام شده'), ('CANCELED', 'کنسل شده'), ('WAITING', 'منتظر')], max_length=50, verbose_name='وضعیت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='پروژه')),
                ('referring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارجاع دهنده')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول کار')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', django_jalali.db.models.jDateTimeField(verbose_name='زمان ثبت')),
                ('referral_description', models.TextField(verbose_name='توضیح ارجاع')),
                ('receiving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارجاع گیرنده')),
                ('referring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارجاع دهنده')),
            ],
            options={
                'verbose_name': 'ارجاع',
                'verbose_name_plural': 'ارجاعات',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', django_jalali.db.models.jDateTimeField(verbose_name='زمان ثبت')),
                ('action_description', models.TextField(verbose_name='شرح اقدام')),
                ('attachment', models.FileField(upload_to='documents/', verbose_name='پیوست')),
                ('registering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'اقدام',
                'verbose_name_plural': 'اقدامات',
            },
        ),
    ]
